-- MySQL Script generated by MySQL Workbench
-- Thu Aug  3 12:12:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `AddressID` INT NOT NULL,
  `Street` VARCHAR(45) NULL DEFAULT NULL,
  `PostCode` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `State` VARCHAR(45) NULL DEFAULT NULL,
  `Country` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`AddressID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Contact Detalis` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bookings` (
  `BookingID` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `TableNum` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  PRIMARY KEY (`BookingID`),
  INDEX `Customer_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `Customer`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`customers` (`CustomerID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`menu` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ProductName` VARCHAR(45) NOT NULL,
  `Cost` DECIMAL(10,0) NOT NULL,
  `Description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`subcategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subcategories` (
  `SubCategoryID` INT NOT NULL AUTO_INCREMENT,
  `CategoryID` INT NOT NULL,
  `SubCategoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SubCategoryID`),
  INDEX `CategoryID_idx` (`CategoryID` ASC) VISIBLE,
  CONSTRAINT `CategoryID`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `mydb`.`categories` (`CategoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `ProductID` INT NOT NULL AUTO_INCREMENT,
  `Cost` DECIMAL(10,0) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Sub-Category` INT NOT NULL,
  PRIMARY KEY (`ProductID`),
  INDEX `Sub-Category_idx` (`Sub-Category` ASC) VISIBLE,
  CONSTRAINT `Sub-Category`
    FOREIGN KEY (`Sub-Category`)
    REFERENCES `mydb`.`subcategories` (`SubCategoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`shipping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shipping` (
  `ShippingID` INT NOT NULL AUTO_INCREMENT,
  `ShipingMode` VARCHAR(45) NOT NULL,
  `Cost` INT NOT NULL,
  `AddressID` INT NOT NULL,
  `ShippingDate` DATE NOT NULL,
  PRIMARY KEY (`ShippingID`),
  INDEX `Address_idx` (`AddressID` ASC) VISIBLE,
  CONSTRAINT `Address`
    FOREIGN KEY (`AddressID`)
    REFERENCES `mydb`.`address` (`AddressID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `ProductID` INT NOT NULL,
  `Quantity` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  `ShippingID` INT NOT NULL,
  `TotalCost` DECIMAL(10,0) NOT NULL,
  `Discount` INT NULL DEFAULT NULL,
  `OrderPriority` INT NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `ProductID_idx` (`ProductID` ASC) VISIBLE,
  INDEX `CustomerID_idx` (`CustomerID` ASC) VISIBLE,
  INDEX `ShippingID_idx` (`ShippingID` ASC) VISIBLE,
  CONSTRAINT `CustomerID`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`customers` (`CustomerID`),
  CONSTRAINT `ProductID`
    FOREIGN KEY (`ProductID`)
    REFERENCES `mydb`.`products` (`ProductID`),
  CONSTRAINT `ShippingID`
    FOREIGN KEY (`ShippingID`)
    REFERENCES `mydb`.`shipping` (`ShippingID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `EmployeeID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Salary` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`EmployeeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`orderstatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orderstatus` (
  `OrderID` INT NOT NULL,
  `DeliveryDate` DATE NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `EmployeeAssigned` INT NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `Employee_idx` (`EmployeeAssigned` ASC) VISIBLE,
  CONSTRAINT `Employee`
    FOREIGN KEY (`EmployeeAssigned`)
    REFERENCES `mydb`.`staff` (`EmployeeID`),
  CONSTRAINT `Order`
    FOREIGN KEY (`OrderID`)
    REFERENCES `mydb`.`orders` (`OrderID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

USE `mydb` ;

-- -----------------------------------------------------
-- procedure AddBooking
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddBooking`(in
NewCustomerID int,
NewTableID int,
bookingdate date
)
begin
	insert into mydb.Bookings (CustomerID, TableNum, `date`)
	values (NewCustomerID, NewTableID, bookingdate);
end$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CancelBooking
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `CancelBooking`(in
NewBookingID int
)
begin
	delete from mydb.Bookings
	where BookingID = NewBookingID;
end$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UpdateBooking
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UpdateBooking`(in
NewBookingID int,
bookingdate date
)
begin
	update mydb.Bookings
	set bookings.`date` = bookingdate 
	where BookingID = NewBookingID;
end$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
